config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get "about" => 'pages#about'
  
  resources :stations
  

end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @home_station = Station.order("RANDOM()").first
  end
  
  def about
    
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index 
    @stations = Station.all
  end
  
  def show 
    set_station
  end
  
  private
  def set_station
    @station = Station.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicStationsApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div class="page-header header">
        Mixes
      </div>
    </header>
    <section>
      <div class="container">
        <%= yield %>
      </div>
    </section>
    <div class="footer">
      <div class="container">
        <p class="footer-block">&copy; Saarim Zaman 2017 | <%= link_to "About", about_path %></p>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12">
      <div class="well well-lg text-center">
        <h1 class="about__header">About this app</h1>
        <p class="about__description">This is a simple app that plays playlists from Soundcloud.</p>
        <%= link_to 'Back to home', root_path, class: "btn btn-small btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row text-center">
  <div class="now_playing">
    <div class="now_playing__title">
      <h3><strong>Now playing</strong>: <a href="/stations/<%= @home_station.id %>"><%= @home_station.title %></a></h3>
    </div>
    <div class="now_playing__content">
      <iframe width="100%" height="400" scrolling="no" frameborder="no" src=<%= @home_station.url %>></iframe>
    </div>
  </div>
  <%= link_to 'Go to all stations', stations_path, class: "btn btn-md btn-primary" %>
</div>

app/views/stations/index.html.erb
<h1>Stations</h1>

<div class="station__container">
  <% @stations.each do |station| %>
  <div class="station__box">
    <h3 align="center" class="station__title"><%= station.title %></h3>
    <%= link_to "Go to Station", station_path(station), class: "btn btn-success station__link" %>
  </div>
  <% end %>
</div>


<%= link_to "Back to home", root_path, class: "btn btn-primary" %>

app/views/stations/show.html.erb
<h1><%= @station.title %></h1>

<%= link_to "Back to all stations", stations_path, class: "btn btn-info" %>

<h3><%= @station.description %></h3>
<iframe width="100%" height="300" scrolling="no" frameborder="no" src=<%= @station.url %>></iframe>